<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ResurectPhone.Core\ResurectPhone.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <InternalsVisibleTo Include="ResurectPhone.Infrastructure.Windows.Tests" />
  </ItemGroup>
</Project>
